service_account_filename: "src/firebase/firebase_config.json"
scopes:
  - "https://www.googleapis.com/auth/cloud-platform"
base_url: "https://fcm.googleapis.com"
batch_url: "https://fcm.googleapis.com/batch"
token_url: "https://oauth2.googleapis.com/token"
fcm_endpoint: "/v1/projects/{}/messages:send"
project_id: "iqtek-push-notifications-app"
